// The lock on a locked spec (Agree, Appendix B): node tools/features-lock.mjs FEATURES.json
// [--root DIR] [--write]
//
// A locked spec is a features.json whose every feature has a stable id, the decision it rests on
// (a gap in the Ask stage's decisions record, decided) and the test that proves it. This fails when:
//   - a feature has no proof test, or names one that doesn't exist or that no runner collects
//     (tools/proofs.mjs, the work list's rule from chapter 10), unless the feature is dropped;
//   - a feature names no decision, or one the record doesn't have, or one still open;
//   - a feature is malformed, two share an id, or a <...> placeholder is left;
//   - an id the states document lists is gone from features.json: a locked feature keeps its id
//     for good, and one that won't be built is set to dropped, with the decision that dropped it;
//   - the states document isn't what this script writes from features.json now.
// The states document is generated, like the lab's API contract (chapter 7): --write rewrites it,
// and only when everything else passes, so it never records a spec that fails its lock.
//
// Paths in features.json (the decisions record, the states document) are from its own folder;
// proofs are from the repository's root, --root, by default the folder this runs in.
// Exit codes: 0 locked, 1 problems, 2 usage or a file that can't be read.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { listFiles } from "./harness-inventory.mjs";
import { proofProblem } from "./proofs.mjs";

const FIELDS = ["id", "description", "status", "decision", "proof"];
const STATUSES = ["todo", "in-progress", "done", "dropped"];
const PLACEHOLDER = /<(?![!/]|https?:)[^<>\n]{1,200}>/g;

function readJson(path, what) {
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch (error) {
    throw new Error(`${what} ${path} can't be read as JSON: ${error.message}`);
  }
}

// The states document for these features: one row each, in the list's order, and the counts.
export function statesDocument(spec, specName) {
  const cell = (text) => String(text ?? "").replaceAll("|", "\\|").replaceAll("\n", " ");
  const rows = spec.features.map(
    (f) => `| ${f.id} | ${cell(f.description)} | ${f.status} | ${f.decision} | ${f.proof ? `\`${cell(f.proof)}\`` : "none"} |`,
  );
  const count = (status) => spec.features.filter((f) => f.status === status).length;
  return [
    "# Feature states",
    "",
    `<!-- Generated by node tools/features-lock.mjs from ${specName}. Don't edit it by hand: change ${specName}, then run the script with --write. -->`,
    "",
    "| Feature | What it does | State | Decision | Proof |",
    "|---|---|---|---|---|",
    ...rows,
    "",
    `Done ${count("done")}, in progress ${count("in-progress")}, to do ${count("todo")}, dropped ${count("dropped")}.`,
    "",
  ].join("\n");
}

// The ids a states document lists: what the spec had locked when it was last written.
export const lockedIds = (text) => [...text.matchAll(/^\| (F\d+) \|/gm)].map((m) => m[1]);

export function checkSpec(specPath, root) {
  const problems = [];
  const where = relative(process.cwd(), specPath).replaceAll("\\", "/") || specPath;
  const spec = readJson(specPath, "The locked spec");
  if (!Array.isArray(spec?.features)) return { problems: [`${where}: needs a "features" list.`], spec, states: null };
  const extra = Object.keys(spec).filter((k) => !["about", "decisions", "states", "features"].includes(k));
  if (extra.length) problems.push(`${where}: unknown field(s) ${extra.join(", ")}; a locked spec has about, decisions, states and features.`);
  for (const key of ["decisions", "states"]) {
    if (typeof spec[key] !== "string" || !spec[key]) problems.push(`${where}: needs "${key}", the path of its ${key === "decisions" ? "decisions record" : "states document"} from this folder.`);
  }
  if (problems.length) return { problems, spec, states: null };
  const folder = dirname(specPath);
  const decisionsPath = join(folder, spec.decisions);
  const statesPath = join(folder, spec.states);
  let gaps = new Map();
  if (!existsSync(decisionsPath)) {
    problems.push(`${where}: its decisions record, ${spec.decisions}, doesn't exist.`);
  } else {
    const record = readJson(decisionsPath, "The decisions record");
    gaps = new Map((Array.isArray(record?.gaps) ? record.gaps : []).map((g) => [g?.id, g]));
  }
  const tracked = new Set(listFiles(root));
  const seen = new Set();
  spec.features.forEach((f, i) => {
    const label = `${where}: ${typeof f?.id === "string" && f.id ? f.id : `feature ${i + 1}`}`;
    if (f === null || typeof f !== "object") {
      problems.push(`${label}: isn't an object.`);
      return;
    }
    const unknown = Object.keys(f).filter((k) => !FIELDS.includes(k));
    const missing = FIELDS.filter((k) => !(k in f));
    if (unknown.length || missing.length) {
      const said = [unknown.length ? `unknown field(s) ${unknown.join(", ")}` : "", missing.length ? `missing ${missing.join(", ")}` : ""];
      problems.push(`${label}: ${said.filter(Boolean).join("; ")}. A feature has ${FIELDS.join(", ")}.`);
    }
    const left = FIELDS.map((k) => f[k]).filter((v) => typeof v === "string").flatMap((v) => [...v.matchAll(PLACEHOLDER)].map((m) => m[0]));
    for (const p of left) problems.push(`${label}: "${p}" is still a placeholder. Replace it with the real thing.`);
    if (left.length) return;
    if (typeof f.id !== "string" || !/^F\d+$/.test(f.id)) problems.push(`${label}: its id must be F and a number, such as F3.`);
    else if (seen.has(f.id)) problems.push(`${label}: another feature has the same id. Ids are never reused.`);
    seen.add(f.id);
    if (typeof f.description !== "string" || !f.description.trim()) problems.push(`${label}: needs a description a test could prove.`);
    if (!STATUSES.includes(f.status)) problems.push(`${label}: its status is ${JSON.stringify(f.status)}; use one of ${STATUSES.join(", ")}.`);
    const gap = gaps.get(f.decision);
    if (typeof f.decision !== "string" || !f.decision) {
      problems.push(`${label}: names no decision. Every feature rests on a decision in ${spec.decisions}: name its gap, such as G1.`);
    } else if (!gap) {
      problems.push(`${label}: its decision, ${f.decision}, isn't in ${spec.decisions}.`);
    } else if (gap.decision === null || gap.decision === undefined) {
      problems.push(`${label}: its decision, ${f.decision}, is still open in ${spec.decisions}. Decide it before the feature is locked.`);
    }
    if (f.status === "dropped") return;
    if (typeof f.proof !== "string" || !f.proof) {
      problems.push(`${label}: has no proof test. Name the test that proves it (<test file>::<test name>) before it's locked, or drop it with its decision.`);
    } else {
      const problem = proofProblem(f.proof, root, tracked);
      if (problem) problems.push(`${label}: ${problem} Write the test first, or point the proof at the one that proves the feature.`);
    }
  });
  // Stable ids: nothing the states document listed may disappear.
  const states = existsSync(statesPath) ? readFileSync(statesPath, "utf8").replaceAll("\r\n", "\n") : null;
  const ids = new Set(spec.features.map((f) => f?.id));
  for (const id of states ? lockedIds(states) : []) {
    if (!ids.has(id)) {
      problems.push(`${where}: ${id} was locked (${spec.states} lists it) and is gone. A locked feature keeps its id: set its status to dropped, with the decision that dropped it.`);
    }
  }
  return { problems, spec, states, statesPath };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const at = args.indexOf("--root");
  const root = at >= 0 ? args[at + 1] : ".";
  const write = args.includes("--write");
  const files = args.filter((a, i) => !a.startsWith("--") && !(at >= 0 && i === at + 1));
  if (files.length !== 1 || (at >= 0 && !root)) {
    console.error("Usage: node tools/features-lock.mjs FEATURES.json [--root DIR] [--write]");
    process.exit(2);
  }
  const specPath = files[0];
  let result;
  try {
    result = checkSpec(specPath, root);
  } catch (error) {
    console.error(`features-lock: ${error.message}`);
    process.exit(2);
  }
  const { problems, spec, states, statesPath } = result;
  console.log(`Locked spec: ${specPath}\n`);
  const expected = statesPath && problems.length === 0 ? statesDocument(spec, basename(specPath)) : null;
  if (expected && write && states !== expected) {
    writeFileSync(statesPath, expected);
    console.log(`Wrote ${spec.states}.`);
  } else if (expected && states !== expected) {
    problems.push(
      `${spec.states} isn't what features.json says now${states === null ? " (it doesn't exist)" : ""}. ` +
        `Run node tools/features-lock.mjs ${specPath} --write, and commit it with the change.`,
    );
  }
  if (problems.length) {
    console.log(`${problems.length} problem(s):`);
    for (const p of problems) console.log(`- ${p}`);
    if (write) console.log(`\n${spec?.states ?? "The states document"} wasn't written: the spec must pass its lock first.`);
    process.exit(1);
  }
  const count = (s) => spec.features.filter((f) => f.status === s).length;
  console.log(`${spec.features.length} feature(s), each with a decision and, unless dropped, a proof test that exists.`);
  console.log(`Done ${count("done")}, in progress ${count("in-progress")}, to do ${count("todo")}, dropped ${count("dropped")}.`);
  console.log("No problems found.");
}
