// The guards this repository breaks on purpose, for tools/mutate.mjs (chapter 24). Each entry names
// the guard, the file and the exact text to change, what to change it to, and the test command that
// must then fail. Add entries when a chapter adds a guard. Chapters 9, 11 to 14, 16 to 18, 24, 25
// and 30 are here, the script tests' git runner (tools/git-run.mjs), chapter 7's consumer test and
// chapter 1's tally's check for missing fields; the guards from earlier chapters were broken by
// hand when they were built (CHANGELOG.md records each time) and are the next candidates to add.

const pytest = (...tests) => ({ cwd: "python", python: ["-m", "pytest", "-q", "-p", "no:cacheprovider", ...tests] });
const vitest = (file, name) => ({ cwd: "ts", vitest: [file, "-t", name] });
// One Node test, by the start of its name.
const nodeTest = (file, name) => ({ node: ["--test", "--test-name-pattern", `^${name}`, file] });

const LAYERS = "tests/guardrails/test_layers_contract.py";
const LINT = "tests/test_helpdesk_lint.py";
const POLICY = "tests/test_agent_policy.py";
const fixture = (name) => pytest(`${POLICY}::test_each_fixture_gets_exactly_the_verdict_it_names[${name}]`);
const DC = "ts/.dependency-cruiser.cjs";
const ESLINT = "ts/eslint.config.js";
const RULE = "ts/scripts/eslint-rules/cli-output-through-write.ts";
const MODEL_TEXT = "python/src/helpdesk_lint/model_text.py";
const AGENT_RULES = "python/src/agent_policy/rules.py";
const FEEDBACK_TESTS = "tools/feedback.test.mjs";
const STOP_TESTS = "tools/hooks/stop-check.test.mjs";
const LOOP_TESTS = "tools/fix-loop.test.mjs";
const REWORK = "tools/rework.mjs";
const REWORK_TESTS = "tools/rework.test.mjs";
const RETRIEVAL = "python/src/helpdesk/services/retrieval.py";
const RETRIEVAL_TESTS = "tests/test_retrieval.py";
const KB_CLI = "python/src/helpdesk/kb.py";
const KB_CLI_TESTS = "tests/test_kb_cli.py";
const CITATIONS = "python/src/helpdesk/services/citations.py";
const CITATIONS_TESTS = "tests/test_citations.py";
const ACCESS = "python/src/helpdesk/services/access.py";
const TICKETS = "python/src/helpdesk/services/tickets.py";
const TOOLS = "python/src/helpdesk/assistant/tools.py";
const ADAPTER = "python/src/helpdesk/model/anthropic_client.py";
const TOOL_ACCESS = "tests/test_tool_access.py";
const TOOL_ARGS = "tests/test_tool_arguments.py";
const TOOL_RESULTS = "tests/test_tool_results.py";
const TOOL_DEFS = "tests/fitness/test_tool_definitions.py";
const ADAPTER_TESTS = "tests/test_anthropic_client.py";
const MCP_SERVER = "python/src/helpdesk/mcp_server.py";
const MCP = "tests/test_mcp_server.py";
const TOKENS = "python/src/mcp_governance/tokens.py";
const FRONT_DOOR = "python/src/mcp_governance/resource_server.py";
const CATALOG = "python/src/mcp_governance/catalog.py";
const TOKEN_TESTS = "tests/test_mcp_tokens.py";
const HTTP_TESTS = "tests/test_mcp_http.py";
const CATALOG_TESTS = "tests/test_mcp_catalog.py";
const catalogFixture = (name) => pytest(`${CATALOG_TESTS}::test_each_fixture_gets_exactly_the_verdict_it_names[${name}]`);
const REVISE = "python/src/helpdesk/assistant/revise.py";
const TEAM = "python/src/helpdesk/assistant/team.py";
const REVISE_TESTS = "tests/test_revise.py";
const TEAM_TESTS = "tests/test_team.py";
const PROTECTED_MJS = "tools/protected.mjs";
const PROTECTED_TESTS = "tools/protected.test.mjs";
const ROUTES_FITNESS = "python/tests/fitness/test_routes_declare_response_models.py";
const ROUTES_FITNESS_TEST = "tests/fitness/test_routes_declare_response_models.py";
const FAKE_FITNESS = "python/tests/fitness/test_tests_fake_the_model_client.py";
const FAKE_FITNESS_TEST = "tests/fitness/test_tests_fake_the_model_client.py";
const PROGRESS = "tools/progress.mjs";
const progressTest = (name) => nodeTest("tools/progress.test.mjs", name);
// The git runner the script tests build their repositories with, proved by tools/git-run.test.mjs.
const GIT_RUN = "tools/git-run.mjs";
const gitRunTest = (name) => nodeTest("tools/git-run.test.mjs", name);

export const MUTATIONS = [
  // Chapter 3, after the 2026-09-30 review: an id too big for SQLite is one that doesn't exist.
  {
    guard: "data: a ticket number too big for SQLite is a missing ticket",
    file: "python/src/helpdesk/data/repository.py",
    find: "    if ticket_id not in IDS:\n        return None\n",
    replace: "",
    run: pytest(
      "tests/test_triage_tools.py::test_a_ticket_number_too_big_for_sqlite_is_a_ticket_that_doesnt_exist",
      "tests/test_api.py::test_an_id_too_big_for_sqlite_is_one_that_does_not_exist",
    ),
  },
  {
    guard: "data: a customer id too big for SQLite is a missing customer",
    file: "python/src/helpdesk/data/repository.py",
    find: "    if customer_id not in IDS:\n        return False\n",
    replace: "",
    run: pytest("tests/test_api.py::test_an_id_too_big_for_sqlite_is_one_that_does_not_exist"),
  },
  {
    guard: "data: a staff id too big for SQLite is a missing member of staff",
    file: "python/src/helpdesk/data/repository.py",
    find: "    if staff_id not in IDS:\n        return False\n",
    replace: "",
    run: pytest("tests/test_api.py::test_an_id_too_big_for_sqlite_is_one_that_does_not_exist"),
  },
  {
    guard: "data: the ids SQLite can store are 8 bytes, signed",
    file: "python/src/helpdesk/data/repository.py",
    find: "IDS = range(-(2**63), 2**63)",
    replace: "IDS = range(-(2**63), 2**64)",
    run: pytest("tests/test_triage_tools.py::test_a_ticket_number_too_big_for_sqlite_is_a_ticket_that_doesnt_exist"),
  },

  // Chapter 16: import rules in Python.
  {
    guard: "import-linter: only helpdesk.model imports the anthropic SDK",
    file: "python/pyproject.toml",
    find: 'allowed_importers = ["helpdesk.model"]',
    replace: 'allowed_importers = ["helpdesk"]',
    run: pytest(`${LAYERS}::test_a_service_importing_the_sdk_is_caught_with_the_fix`, `${LAYERS}::test_a_module_written_after_the_contract_is_covered_too`),
  },
  {
    guard: "import-linter: the SDK contract says how to fix it",
    file: "python/pyproject.toml",
    find: 'broken_contract_guidance = "Code outside helpdesk.model must not call the vendor directly. Take a ModelClient as an argument instead, so tests can pass the mock and refusals go through helpdesk.model.stops; if the model needs something new, add it to helpdesk.model."\n',
    replace: "",
    run: pytest(`${LAYERS}::test_a_service_importing_the_sdk_is_caught_with_the_fix`),
  },
  {
    guard: "import-linter: the data-layer contract says how to fix it",
    file: "python/pyproject.toml",
    find: 'broken_contract_guidance = "Code that needs data must call a service: move the query into helpdesk.services and call that from the route or the tool."\n',
    replace: "",
    run: pytest(`${LAYERS}::test_route_importing_the_data_layer_is_caught_with_the_fix`),
  },
  {
    guard: "import-linter: installed packages are in the import graph",
    file: "python/pyproject.toml",
    find: "include_external_packages = true\n",
    replace: "",
    run: pytest(`${LAYERS}::test_clean_copy_keeps_every_contract`),
  },

  // Chapter 16: import rules in TypeScript.
  {
    guard: "dependency-cruiser: imports used only for types count",
    file: DC,
    find: "tsPreCompilationDeps: true,",
    replace: "tsPreCompilationDeps: false,",
    run: vitest("test/boundaries.test.ts", "catches an import that exists only for types"),
  },
  {
    guard: "dependency-cruiser: process.getBuiltinModule() counts as an import",
    file: DC,
    find: "detectProcessBuiltinModuleCalls: true,",
    replace: "detectProcessBuiltinModuleCalls: false,",
    run: vitest("test/boundaries.test.ts", "catches a Node built-in in the client, however it is loaded"),
  },
  {
    guard: "dependency-cruiser: the client doesn't import the CLI",
    file: DC,
    find: 'from: { path: "^src/client[.]ts$" },\n      to: { path: "^src/cli[.]ts$" },',
    replace: 'from: { path: "^nothing$" },\n      to: { path: "^src/cli[.]ts$" },',
    run: vitest("test/boundaries.test.ts", "catches the same import written as a dynamic import"),
  },
  {
    guard: "dependency-cruiser: a rule's comment says how to fix it",
    file: DC,
    find: " Move what both need into client.ts or types.ts.",
    replace: "",
    run: vitest("test/boundaries.test.ts", "catches the client importing the CLI, and says how to fix it"),
  },
  {
    guard: "dependency-cruiser: the types import nothing above them",
    file: DC,
    find: 'to: { path: "^src/(client|cli)[.]ts$" },',
    replace: 'to: { path: "^nothing$" },',
    run: vitest("test/boundaries.test.ts", "catches an import that exists only for types"),
  },
  {
    guard: "dependency-cruiser: only types.ts imports the generated file",
    file: DC,
    find: 'from: { pathNot: "^src/types[.]ts$" },',
    replace: 'from: { pathNot: "^src/(types|cli)[.]ts$" },',
    run: vitest("test/boundaries.test.ts", "catches the CLI importing the generated file directly"),
  },
  {
    guard: "dependency-cruiser: only the CLI uses Node's built-ins",
    file: DC,
    find: 'to: { dependencyTypes: ["core"] },',
    replace: 'to: { path: "^nothing$" },',
    run: vitest("test/boundaries.test.ts", "catches a Node built-in in the client, however it is loaded"),
  },
  {
    guard: "dependency-cruiser: src doesn't import scripts or tests",
    file: DC,
    find: 'to: { path: "^(scripts|test)/" },',
    replace: 'to: { path: "^nothing$" },',
    run: vitest("test/boundaries.test.ts", "catches the package importing a script"),
  },
  {
    guard: "dependency-cruiser: the folders cruised are read from the tree, not listed",
    file: "ts/test/boundaries.test.ts",
    find: "    .filter(hasTypeScript)\n",
    replace: '    .filter((name) => ["src", "scripts", "test"].includes(name))\n',
    run: vitest("test/boundaries.test.ts", "covers a folder added later"),
  },
  {
    guard: "dependency-cruiser: npm run deps cruises every folder with TypeScript in it",
    file: "ts/package.json",
    find: '"deps": "depcruise src scripts test --config',
    replace: '"deps": "depcruise src test --config',
    run: vitest("test/boundaries.test.ts", "cruises every top-level folder"),
  },
  {
    guard: "dependency-cruiser: no circular imports",
    file: DC,
    find: "to: { circular: true },",
    replace: 'to: { path: "^nothing$" },',
    run: vitest("test/boundaries.test.ts", "catches files that import each other in a circle"),
  },
  {
    guard: "dependency-cruiser: the test checks every file was read",
    file: "ts/test/boundaries.test.ts",
    find: "[DEPCRUISE, ...folders,",
    replace: '[DEPCRUISE, "src", "test",',
    run: vitest("test/boundaries.test.ts", "reads every TypeScript file in the package"),
  },
  {
    guard: "ESLint: built-ins are caught under their bare names too",
    file: ESLINT,
    find: "const NODE_BUILTINS = [...BARE, ",
    replace: "const NODE_BUILTINS = [",
    run: vitest("test/boundaries.test.ts", "under either name"),
  },
  {
    guard: "ESLint: the built-ins rule covers files written later",
    file: ESLINT,
    find: 'files: ["src/**/*.ts"],',
    replace: 'files: ["src/client.ts", "src/types.ts", "src/api-types.ts"],',
    run: vitest("test/boundaries.test.ts", "covers a file in src/ that doesn't exist yet"),
  },
  {
    guard: "ESLint: the CLI may use Node's built-ins",
    file: ESLINT,
    find: 'ignores: ["src/cli.ts"],',
    replace: "ignores: [],",
    run: vitest("test/boundaries.test.ts", "lets the CLI import them"),
  },
  {
    guard: "ESLint: every TypeScript file is linted",
    file: ESLINT,
    find: 'files: ["**/*.ts"],',
    replace: 'files: ["src/**/*.ts"],',
    run: vitest("test/boundaries.test.ts", "lints every TypeScript file in the package"),
  },

  // Chapter 17: the Python model-text rule.
  {
    guard: "HDK101: results of .complete() are tracked",
    file: MODEL_TEXT,
    find: "        if is_complete_call(value):\n            return True\n",
    replace: "        if False:\n            return True\n",
    run: pytest(`${LINT}::test_reading_the_text_after_complete_is_caught_and_the_message_says_what_to_do`),
  },
  {
    guard: "HDK101: a plain alias of a response is followed",
    file: MODEL_TEXT,
    find: "        return isinstance(value, ast.Name) and any(value.id in scope for scope in self.scopes)\n",
    replace: "        return False\n",
    run: pytest(`${LINT}::test_a_response_under_another_name_is_followed`),
  },
  {
    guard: "HDK101: each name of an unpacked tuple is followed",
    file: MODEL_TEXT,
    find: "            for t, v in zip(target.elts, value.elts, strict=True):\n                self._bind(t, v)\n",
    replace: "            pass\n",
    run: pytest(`${LINT}::test_a_response_under_another_name_is_followed`),
  },
  {
    guard: "HDK101: a name the walrus operator binds is followed",
    file: MODEL_TEXT,
    find: "binds r like an assignment.\n        self.generic_visit(node)\n        self._bind(node.target, node.value)\n",
    replace: "binds r like an assignment.\n        self.generic_visit(node)\n",
    run: pytest(`${LINT}::test_a_response_under_another_name_is_followed`),
  },
  {
    guard: "HDK101: text read straight off a walrus is caught",
    file: MODEL_TEXT,
    find: "            elif isinstance(node.value, ast.NamedExpr) and self._responds(node.value.value):",
    replace: "            elif False:",
    run: pytest(`${LINT}::test_a_response_under_another_name_is_followed`),
  },
  {
    guard: "HDK101: ModelResponse annotations are recognized",
    file: MODEL_TEXT,
    find: '        if isinstance(node, ast.Name) and node.id == "ModelResponse":',
    replace: '        if isinstance(node, ast.Name) and node.id == "NotModelResponse":',
    run: pytest(`${LINT}::test_a_parameter_annotated_as_a_model_response_is_caught`),
  },
  {
    guard: "HDK101: text read straight off the call is caught",
    file: MODEL_TEXT,
    find: "            elif is_complete_call(node.value):\n                self.reads.append",
    replace: "            elif False:\n                self.reads.append",
    run: pytest(`${LINT}::test_reading_the_text_straight_off_the_call_is_caught`),
  },
  {
    guard: "HDK101: each function has its own scope",
    file: MODEL_TEXT,
    find: "        self.scopes.append(responses)\n        self.generic_visit(node)\n        self.scopes.pop()",
    replace: "        self.scopes[-1].update(responses)\n        self.generic_visit(node)",
    run: pytest(`${LINT}::test_a_name_in_another_function_is_not_a_model_response`),
  },
  {
    guard: "HDK101: only model responses are flagged, not every .text",
    file: MODEL_TEXT,
    find: "            if isinstance(node.value, ast.Name) and any(node.value.id in scope for scope in self.scopes):",
    replace: "            if isinstance(node.value, ast.Name):",
    run: pytest(`${LINT}::test_final_text_and_other_objects_text_pass`),
  },
  {
    guard: "HDK102: an exception needs a reason",
    file: MODEL_TEXT,
    find: "        elif not exemption.reason:",
    replace: "        elif False:",
    run: pytest(`${LINT}::test_an_exception_without_a_reason_fails`),
  },
  {
    guard: "HDK103: a stale exception fails",
    file: MODEL_TEXT,
    find: "        if covered not in read_lines:\n            problems.append(Problem(exemption.line, 1, STALE))",
    replace: "        if covered not in read_lines:\n            pass",
    run: pytest(`${LINT}::test_an_exception_where_nothing_reads_the_text_fails`),
  },
  {
    guard: "HDK101: an exception may sit on the line above",
    file: MODEL_TEXT,
    find: "        covered = line + 1 if alone else line",
    replace: "        covered = line",
    run: pytest(`${LINT}::test_an_exception_with_a_reason_is_accepted_on_the_line_or_just_above_it`),
  },
  {
    guard: "HDK101: the message says what to do",
    file: MODEL_TEXT,
    find: '"recording the turn, put the reason on it: # HDK101: <why>"',
    replace: '"recording the turn."',
    run: pytest(`${LINT}::test_reading_the_text_after_complete_is_caught_and_the_message_says_what_to_do`),
  },
  {
    guard: "helpdesk_lint: a run that read no files fails",
    file: "python/src/helpdesk_lint/__main__.py",
    find: "        return 2\n",
    replace: "        return 0\n",
    run: pytest(`${LINT}::test_the_model_package_is_exempt_and_a_run_that_checks_nothing_fails`),
  },
  {
    guard: "helpdesk_lint: the model package is exempt",
    file: "python/src/helpdesk_lint/__main__.py",
    find: 'EXEMPT_PACKAGE = ("helpdesk", "model")',
    replace: 'EXEMPT_PACKAGE = ("helpdesk", "nothing")',
    run: pytest(`${LINT}::test_the_helpdesk_passes_with_one_exception_that_says_why`),
  },
  {
    guard: "helpdesk_lint: the agent loop's exception carries its reason",
    file: "python/src/helpdesk/assistant/agent.py",
    find: "        # HDK101: the turn goes into the transcript as it came; the answer goes through final_text below.\n",
    replace: "",
    run: pytest(`${LINT}::test_the_helpdesk_passes_with_one_exception_that_says_why`),
  },

  // Chapter 17: the custom ESLint rule.
  {
    guard: "cli-output-through-write: console.error is only suggested, never fixed",
    file: RULE,
    find: 'if (method === "log" && oneArgument) {',
    replace: "if (oneArgument) {",
    run: vitest("test/lint-rules.test.ts", "console.error"),
  },
  {
    guard: "cli-output-through-write: console.log is fixed",
    file: RULE,
    find: 'context.report({ node, messageId: "useWrite", data: { method }, fix: toWrite });',
    replace: 'context.report({ node, messageId: "useWrite", data: { method } });',
    run: vitest("test/lint-rules.test.ts", "console.log"),
  },
  {
    guard: "cli-output-through-write: only a write parameter counts",
    file: RULE,
    find: 'if (variable) return variable.defs.some((definition) => definition.type === "Parameter");',
    replace: "if (variable) return true;",
    run: vitest("test/lint-rules.test.ts", "const write"),
  },
  {
    guard: "cli-output-through-write: write is found in enclosing functions",
    file: RULE,
    find: "for (let current = scope; current; current = current.upper) {",
    replace: "for (let current = scope; current; current = null) {",
    run: vitest("test/lint-rules.test.ts", "fixes a console.log planted"),
  },
  {
    guard: "cli-output-through-write: the message says why",
    file: RULE,
    find: " This function takes write so that tests can read its output; console.{{method}} goes straight to the terminal, where no test sees it.",
    replace: "",
    run: vitest("test/lint-rules.test.ts", "console.log"),
  },
  {
    guard: "cli-output-through-write: the rule is switched on",
    file: ESLINT,
    find: 'rules: { "local/cli-output-through-write": "error" },',
    replace: 'rules: { "local/cli-output-through-write": "off" },',
    run: vitest("test/lint-rules.test.ts", "fixes a console.log planted"),
  },

  // Chapter 18: the policy for agent definitions.
  {
    guard: "agent policy: the cost rule",
    file: AGENT_RULES,
    find: "        if cost > cap:",
    replace: "        if False:",
    run: fixture("fail-too-many-tokens-for-the-model"),
  },
  {
    guard: "agent policy: the cost depends on the model",
    file: AGENT_RULES,
    find: 'price = Decimal(str(models[model]["output_usd_per_million"]))',
    replace: 'price = Decimal("20.0")',
    run: fixture("pass-cheaper-model-more-tokens"),
  },
  {
    guard: "agent policy: unknown fields are reported",
    file: AGENT_RULES,
    find: "        if key not in FIELDS:",
    replace: "        if False:",
    run: fixture("fail-misspelled-field"),
  },
  {
    guard: "agent policy: true isn't a number",
    file: AGENT_RULES,
    find: "    return isinstance(value, kind) and not isinstance(value, bool)",
    replace: "    return isinstance(value, kind)",
    run: fixture("fail-true-is-not-a-number"),
  },
  {
    guard: "agent policy: empty text is refused",
    file: AGENT_RULES,
    find: "        elif kind is str and not definition[key].strip():",
    replace: "        elif False:",
    run: fixture("fail-empty-prompt"),
  },
  {
    guard: "agent policy: only approved models",
    file: AGENT_RULES,
    find: "    if model is not None and model not in models:",
    replace: "    if False:",
    run: fixture("fail-model-not-approved"),
  },
  {
    guard: "agent policy: every problem is reported, not only the first",
    file: AGENT_RULES,
    find: "\n    return found\n",
    replace: "\n    return found[:1]\n",
    run: fixture("fail-several-at-once"),
  },
  {
    guard: "agent policy: only known tools",
    file: AGENT_RULES,
    find: '        elif tool not in policy["tools"]:',
    replace: "        elif False:",
    run: fixture("fail-unknown-tool"),
  },
  {
    guard: "agent policy: the turn limit",
    file: AGENT_RULES,
    find: "    elif max_turns is not None and max_turns > limit:",
    replace: "    elif False:",
    run: fixture("fail-too-many-turns"),
  },
  {
    guard: "agent policy: the turn limit itself is allowed",
    file: AGENT_RULES,
    find: "    elif max_turns is not None and max_turns > limit:",
    replace: "    elif max_turns is not None and max_turns >= limit:",
    run: fixture("pass-turns-at-the-limit"),
  },
  {
    guard: "agent policy: one turn over the limit is refused",
    file: AGENT_RULES,
    find: "    elif max_turns is not None and max_turns > limit:",
    replace: "    elif max_turns is not None and max_turns > limit + 1:",
    run: fixture("fail-turns-one-over-the-limit"),
  },
  {
    guard: "agent policy: every rule is registered",
    file: AGENT_RULES,
    find: '    "empty": "a text field left empty",\n',
    replace: "",
    run: pytest(`${POLICY}::test_every_rule_is_shown_failing_by_some_fixture`),
  },
  {
    guard: "agent policy: every rule has a failing fixture",
    file: AGENT_RULES,
    find: '    "tool": "a tool the platform doesn\'t provide",\n',
    replace: '    "tool": "a tool the platform doesn\'t provide",\n    "unused": "a rule nothing tests",\n',
    run: pytest(`${POLICY}::test_every_rule_is_shown_failing_by_some_fixture`),
  },
  {
    guard: "agent policy: the triage assistant checks before it runs",
    file: "python/src/helpdesk/triage.py",
    find: "    violations = check(agent, load(POLICY))",
    replace: "    violations = []",
    run: pytest(`${POLICY}::test_the_triage_assistant_refuses_a_definition_that_breaks_the_policy`),
  },
  {
    guard: "agent policy: the check sees this run's --max-turns",
    file: "python/src/helpdesk/triage.py",
    find: '    if args.max_turns is not None:\n        agent["max_turns"] = args.max_turns\n    violations = check(agent, load(POLICY))',
    replace: '    violations = check(agent, load(POLICY))\n    if args.max_turns is not None:\n        agent["max_turns"] = args.max_turns',
    run: pytest(`${POLICY}::test_the_triage_assistant_checks_the_turn_limit_it_is_given_too`),
  },
  {
    guard: "agent policy: its prices match the code",
    file: "python/agents/policy.toml",
    find: "claude-opus-5-5 = { output_usd_per_million = 20.0 }",
    replace: "claude-opus-5-5 = { output_usd_per_million = 15.0 }",
    run: pytest(`${POLICY}::test_the_policy_prices_match_the_code`),
  },
  {
    guard: "agent policy: its tools match the code",
    file: "python/agents/policy.toml",
    find: 'tools = ["get_ticket", "find_tickets", "search_kb", "delegate_customer"]',
    replace: 'tools = ["get_ticket", "find_tickets", "search_kb", "delegate_customer", "send_email"]',
    run: pytest(`${POLICY}::test_the_policy_tools_are_the_tools_the_code_provides`),
  },
  {
    guard: "agent policy: the fixtures are found",
    file: "python/tests/test_agent_policy.py",
    find: 'FIXTURES_DIR = Path(__file__).parent / "policy_fixtures"',
    replace: 'FIXTURES_DIR = Path(__file__).parent / "policy_fixture"',
    run: pytest(`${POLICY}::test_there_are_fixtures_to_run`),
  },
  {
    guard: "agent policy: a run with nothing to check fails",
    file: "python/src/agent_policy/__main__.py",
    find: "        return 2\n",
    replace: "        return 0\n",
    run: pytest(`${POLICY}::test_a_run_that_finds_no_definitions_fails`),
  },

  // Chapter 24: this runner's own guards.
  {
    guard: "mutate: a nested test command answers for itself",
    file: "tools/mutate.mjs",
    find: "delete ENV.NODE_TEST_CONTEXT;",
    replace: "",
    run: { node: ["--test", "tools/mutate.test.mjs"] },
  },
  {
    guard: "mutate: a test command must pass on the unchanged code first",
    file: "tools/mutate.mjs",
    find: 'if (controls.get(key) !== "pass") {',
    replace: "if (false) {",
    run: { node: ["--test", "tools/mutate.test.mjs"] },
  },
  {
    guard: "mutate: a mutation whose text is gone is stale",
    file: "tools/mutate.mjs",
    find: "if (text.split(m.find).length !== 2) {",
    replace: "if (false) {",
    run: { node: ["--test", "tools/mutate.test.mjs"] },
  },

  // Chapter 25: sending failures back to the agent, and the limits on doing it.
  {
    guard: "feedback: the exit code decides whether the checks passed",
    file: "tools/feedback.mjs",
    find: "return { passed: run.status === 0, output };",
    replace: 'return { passed: !output.includes("FAIL"), output };',
    run: nodeTest(FEEDBACK_TESTS, "the exit code decides"),
  },
  {
    guard: "feedback: the report leaves out the checks that passed",
    file: "tools/feedback.mjs",
    find: '.filter((line) => !line.startsWith("PASS  "))',
    replace: ".filter(() => true)",
    run: nodeTest(FEEDBACK_TESTS, "keeps the failing checks"),
  },
  {
    guard: "feedback: the report is bounded",
    file: "tools/feedback.mjs",
    find: "if (kept.length <= max) return kept;",
    replace: "return kept;",
    run: nodeTest(FEEDBACK_TESTS, "cuts a long report"),
  },
  {
    guard: "feedback: the checks run without the provider's credentials",
    file: "tools/feedback.mjs",
    find: "    env: checkEnvironment(),\n",
    replace: "",
    run: nodeTest(FEEDBACK_TESTS, "the checks run without the provider's credentials"),
  },
  {
    guard: "feedback: an auth token is held back as well as an API key",
    file: "tools/feedback.mjs",
    find: 'export const CREDENTIALS = ["ANTHROPIC_API_KEY", "ANTHROPIC_AUTH_TOKEN"];',
    replace: 'export const CREDENTIALS = ["ANTHROPIC_API_KEY"];',
    run: nodeTest(FEEDBACK_TESTS, "the checks run without the provider's credentials"),
  },
  {
    guard: "feedback: a credential's name is matched without regard to case",
    file: "tools/feedback.mjs",
    find: "if (CREDENTIALS.includes(name.toUpperCase()))",
    replace: "if (CREDENTIALS.includes(name))",
    run: nodeTest(FEEDBACK_TESTS, "the checks run without the provider's credentials"),
  },
  {
    guard: "Stop hook: a failure blocks with exit code 2",
    file: "tools/hooks/stop-decision.mjs",
    find: "return { exitCode: 2, blocks, stderr };",
    replace: "return { exitCode: 1, blocks, stderr };",
    run: nodeTest(STOP_TESTS, "a failure blocks with exit code 2"),
  },
  {
    guard: "Stop hook: three blocks in a row, then the agent may stop",
    file: "tools/hooks/stop-decision.mjs",
    find: "if (blocksSoFar >= MAX_BLOCKS) {",
    replace: "if (false) {",
    run: nodeTest(STOP_TESTS, "after three blocks in a row"),
  },
  {
    guard: "Stop hook: a session id can't choose where the count goes",
    file: "tools/hooks/stop-decision.mjs",
    find: '.replace(/[^A-Za-z0-9_-]/g, "_")',
    replace: "",
    run: nodeTest(STOP_TESTS, "a session id can't choose"),
  },
  {
    guard: "Stop hook: a stop that doesn't follow a block starts counting again",
    file: "tools/hooks/stop-check.mjs",
    find: "const blocksSoFar = input.stop_hook_active ? readBlocks(file) : 0;",
    replace: "const blocksSoFar = readBlocks(file);",
    run: nodeTest(STOP_TESTS, "a stop that doesn't follow a block"),
  },
  {
    guard: "Stop hook: the checks run where the agent is working",
    file: "tools/hooks/stop-check.mjs",
    find: "repositoryRoot(input.cwd ?? process.cwd())",
    replace: "repositoryRoot(process.cwd())",
    run: nodeTest(STOP_TESTS, "a failure blocks with exit code 2"),
  },
  {
    guard: "Stop hook: .claude/settings.json runs a script that exists",
    file: ".claude/settings.json",
    find: '"${CLAUDE_PROJECT_DIR}/tools/hooks/stop-check.mjs"',
    replace: '"${CLAUDE_PROJECT_DIR}/tools/hook/stop-check.mjs"',
    run: nodeTest(STOP_TESTS, "every command hook"),
  },
  {
    guard: "fix loop: the prompt carries the report",
    file: "tools/fix-loop.mjs",
    find: "    failureReport(output),\n",
    replace: '    "(see the checks)",\n',
    run: nodeTest(LOOP_TESTS, "the prompt carries the report"),
  },
  {
    guard: "fix loop: at most the set number of attempts",
    file: "tools/fix-loop.mjs",
    find: "for (let attempt = 1; attempt <= attempts; attempt++) {",
    replace: "for (let attempt = 1; attempt <= attempts + 1; attempt++) {",
    run: nodeTest(LOOP_TESTS, "stops after three attempts"),
  },
  {
    guard: "fix loop: an attempt that changes nothing ends the loop",
    file: "tools/fix-loop.mjs",
    find: "if (withoutTimes(checks.output) === withoutTimes(previous.output)) {",
    replace: "if (false) {",
    run: nodeTest(LOOP_TESTS, "stops at once when an attempt"),
  },
  {
    guard: "fix loop: a change to the checks stops the loop",
    file: "tools/fix-loop.mjs",
    find: "  if (changed.length) {",
    replace: "  if (false) {",
    run: nodeTest(LOOP_TESTS, "stops when the agent changes the checks"),
  },
  {
    guard: "fix loop: check.mjs counts as one of the checks",
    file: PROTECTED_MJS,
    find: "export const ALWAYS = [/^check\\.mjs$/, TOOLS,",
    replace: "export const ALWAYS = [TOOLS,",
    run: nodeTest(LOOP_TESTS, "stops when the agent changes the checks"),
  },

  // Chapter 31: the rework count.
  {
    guard: "rework: a co-author trailer naming an agent counts",
    file: REWORK,
    find: "/\\b(claude|copilot|codex|cursor|devin|gemini|aider|windsurf|jules)\\b/i",
    replace: "/\\b(copilot|codex|cursor|devin|gemini|aider|windsurf|jules)\\b/i",
    run: nodeTest(REWORK_TESTS, "counts agent commits"),
  },
  {
    guard: "rework: so does an agent as the author",
    file: REWORK,
    find: "AGENT.test(commit.author) || ",
    replace: "",
    run: nodeTest(REWORK_TESTS, "counts agent commits"),
  },
  {
    guard: "rework: fixed and fixes count as fixes",
    file: REWORK,
    find: "/^(fix(es|ed)?|hotfix|revert(s|ed)?)\\b/i",
    replace: "/^(fix|hotfix|revert)\\b/i",
    run: nodeTest(REWORK_TESTS, "fix subjects"),
  },
  {
    guard: "rework: a fix to a person's change isn't rework",
    file: REWORK,
    find: "return before && before.agent && commit.time - before.time < within * DAY;",
    replace: "return before && commit.time - before.time < within * DAY;",
    run: nodeTest(REWORK_TESTS, "a fix to a person's change"),
  },
  {
    guard: "rework: nor is a fix to an old agent change",
    file: REWORK,
    find: "return before && before.agent && commit.time - before.time < within * DAY;",
    replace: "return before && before.agent;",
    run: nodeTest(REWORK_TESTS, "a fix to a person's change"),
  },
  {
    guard: "rework: the history reaches back before the window",
    file: REWORK,
    find: "readHistory(root, windowStart - within * DAY, { allFiles, ignore })",
    replace: "readHistory(root, windowStart, { allFiles, ignore })",
    run: nodeTest(REWORK_TESTS, "an agent change just before the window"),
  },
  {
    guard: "rework: Markdown files are left out",
    file: REWORK,
    find: "(allFiles || !MARKDOWN.test(f))",
    replace: "true",
    run: nodeTest(REWORK_TESTS, "Markdown files don't make a fix rework"),
  },
  {
    guard: "rework: --ignore leaves files out",
    file: REWORK,
    find: "!(ignore && ignore.test(f))",
    replace: "true",
    run: nodeTest(REWORK_TESTS, "--ignore leaves out files"),
  },
  {
    guard: "rework: a fix counts once per folder",
    file: REWORK,
    find: "for (const name of new Set(reworked.map((f) => folder(f, depth)))) {",
    replace: "for (const name of reworked.map((f) => folder(f, depth))) {",
    run: nodeTest(REWORK_TESTS, "folders are grouped"),
  },
  {
    guard: "rework: folders go --depth levels deep",
    file: REWORK,
    find: 'parts.slice(0, depth).join("/")',
    replace: 'parts.slice(0, 1).join("/")',
    run: nodeTest(REWORK_TESTS, "folders are grouped"),
  },

  // Chapter 9: retrieval over the knowledge base, its golden-set check, and citation checking.
  {
    guard: "retrieval: every passage carries its article's title and heading",
    file: RETRIEVAL,
    find: 'return f"{self.title} > {self.heading}: {self.text}" if self.heading else f"{self.title}: {self.text}"',
    replace: "return self.text",
    run: pytest(`${RETRIEVAL_TESTS}::test_a_question_can_find_a_passage_through_its_heading`),
  },
  {
    guard: "retrieval: BM25 marks down a longer passage",
    file: RETRIEVAL,
    find: "norm = K1 * (1 - B + B * length / self.average_length)",
    replace: "norm = K1",
    run: pytest(`${RETRIEVAL_TESTS}::test_bm25_marks_down_a_longer_passage_with_the_same_matches`),
  },
  {
    guard: "retrieval: a word in most passages weighs nothing, never less",
    file: RETRIEVAL,
    find: "max(0.0, math.log((n - c + 0.5) / (c + 0.5)))",
    replace: "math.log((n - c + 0.5) / (c + 0.5))",
    run: pytest(`${RETRIEVAL_TESTS}::test_a_word_in_most_passages_adds_nothing_rather_than_counting_against_a_passage`),
  },
  {
    guard: "retrieval: fusion's k = 60 lets agreement beat one ranker's first place",
    file: RETRIEVAL,
    find: "RRF_K = 60",
    replace: "RRF_K = 0",
    run: pytest(`${RETRIEVAL_TESTS}::test_fusion_puts_a_passage_both_rankers_like_above_one_only_a_single_ranker_puts_first`),
  },
  {
    guard: "retrieval: keyword search returns only passages with a word in common",
    file: RETRIEVAL,
    find: "passing = [i for i, s in enumerate(scores) if s > 0]",
    replace: "passing = list(range(len(scores)))",
    run: pytest(`${RETRIEVAL_TESTS}::test_a_question_the_knowledge_base_cannot_answer_gets_nothing_back`),
  },
  {
    guard: "retrieval: the vector ranker returns only passages above its floor",
    file: RETRIEVAL,
    find: "passing = [i for i, s in enumerate(scores) if s >= VECTOR_FLOOR]",
    replace: "passing = list(range(len(scores)))",
    run: pytest(`${RETRIEVAL_TESTS}::test_a_question_the_knowledge_base_cannot_answer_gets_nothing_back`),
  },
  {
    guard: "retrieval eval: recall below the floor fails",
    file: KB_CLI,
    find: 'recall_ok = hybrid.recall >= floor["recall"]',
    replace: "recall_ok = True",
    run: pytest(`${KB_CLI_TESTS}::test_the_eval_fails_when_retrieval_loses_a_question_and_names_it`),
  },
  {
    guard: "retrieval eval: passages for a question with no answer fail",
    file: KB_CLI,
    find: 'empty_ok = empty_share >= floor["no_answer_empty"]',
    replace: "empty_ok = True",
    run: pytest(`${KB_CLI_TESTS}::test_the_eval_fails_when_a_question_with_no_answer_gets_passages`),
  },
  {
    guard: "retrieval eval: a hit must contain the answer, not just come from the right article",
    file: KB_CLI,
    find: 'return any(h.chunk.article_id == answer["article"] and says in h.chunk.text.lower() for h in hits)',
    replace: 'return any(h.chunk.article_id == answer["article"] for h in hits)',
    run: pytest(`${KB_CLI_TESTS}::test_a_passage_from_the_right_article_without_the_answer_is_a_miss`),
  },
  {
    guard: "citations: a citation to a passage that doesn't exist is caught",
    file: CITATIONS,
    find: "if known is not None and citation not in known:",
    replace: "if False:",
    run: pytest(`${CITATIONS_TESTS}::test_a_citation_to_a_passage_that_does_not_exist_is_caught`),
  },
  {
    guard: "citations: a citation to a passage the answer wasn't given is caught",
    file: CITATIONS,
    find: `            elif citation not in given:
                reason = f"[{citation}] wasn't among the passages this answer was given"
                problems.append(Problem(citation, sentence, f"{reason}, so it can't have come from it"))
            else:
                support |= _vocabulary(given[citation])`,
    replace: `            else:
                support |= _vocabulary(given.get(citation, ""))`,
    run: pytest(`${CITATIONS_TESTS}::test_a_citation_to_a_real_passage_the_answer_was_not_given_is_caught`),
  },
  {
    guard: "citations: a sentence using words its passages don't have is caught",
    file: CITATIONS,
    find: "if support and missing:",
    replace: "if False:",
    run: pytest(`${CITATIONS_TESTS}::test_a_changed_fact_is_caught_and_the_word_named`),
  },
  {
    guard: "citations: a citation after the full stop belongs to the sentence before it",
    file: CITATIONS,
    find: "        if lead and found:",
    replace: "        if False:",
    run: pytest(
      `${CITATIONS_TESTS}::test_a_citation_after_the_full_stop_at_the_end_is_checked_against_its_sentence`,
      `${CITATIONS_TESTS}::test_a_citation_after_the_full_stop_mid_answer_stays_with_its_own_sentence`,
    ),
  },
  {
    guard: "citations: a run of citations after the full stop goes back whole",
    file: CITATIONS,
    find: 'LEADING_CITATIONS = re.compile(r"^(?:\\s*[(,;]?\\s*\\[\\d+#\\d+\\]\\s*\\)?)+")',
    replace: 'LEADING_CITATIONS = re.compile(r"^(?:\\s*[(,;]?\\s*\\[\\d+#\\d+\\]\\s*\\)?)")',
    run: pytest(`${CITATIONS_TESTS}::test_citations_after_the_full_stop_all_go_back_to_the_sentence_they_follow`),
  },
  {
    guard: "citations: a citation in parentheses after the full stop goes back too",
    file: CITATIONS,
    find: 'LEADING_CITATIONS = re.compile(r"^(?:\\s*[(,;]?\\s*\\[\\d+#\\d+\\]\\s*\\)?)+")',
    replace: 'LEADING_CITATIONS = re.compile(r"^(?:\\s*[,;]?\\s*\\[\\d+#\\d+\\]\\s*)+")',
    run: pytest(`${CITATIONS_TESTS}::test_a_citation_after_the_full_stop_at_the_end_is_checked_against_its_sentence`),
  },
  {
    guard: "citations: a citation with no sentence to support is a problem",
    file: CITATIONS,
    find: '        if not words(CITATION.sub(" ", sentence)):',
    replace: "        if False:",
    run: pytest(`${CITATIONS_TESTS}::test_a_citation_with_no_sentence_to_support_is_a_problem`),
  },
  {
    guard: "citations: the messages say the check compares words, not meaning",
    file: KB_CLI,
    find: `"and uses only its passage's words."`,
    replace: `"and supports its sentence."`,
    run: pytest(`${KB_CLI_TESTS}::test_cite_passes_a_supported_answer_and_fails_a_changed_fact`),
  },
  {
    guard: "triage: a draft whose citations fail is reported as failing",
    file: "python/src/helpdesk/triage.py",
    find: "    return report.ok\n",
    replace: "    return True\n",
    run: pytest("tests/test_triage_cli.py::test_a_draft_that_changes_what_its_passage_says_is_stopped"),
  },

  // Chapter 11: tools that act for a person, check their arguments, and size their results.
  {
    guard: "access: support staff see their own tickets and the queue, no others",
    file: ACCESS,
    find: 'return ticket["assignee_id"] in (None, person.id)',
    replace: "return True",
    run: pytest(`${TOOL_ACCESS}::test_a_ticket_assigned_to_someone_else_is_refused_inside_the_tool`),
  },
  {
    guard: "access: a role the rule doesn't know sees nothing",
    file: ACCESS,
    find: "    return False  # a role this rule doesn't know sees nothing: it fails closed",
    replace: "    return True",
    run: pytest(`${TOOL_ACCESS}::test_a_role_the_rule_does_not_know_sees_nothing`),
  },
  {
    guard: "access: a hidden ticket gets the same answer as a missing one",
    file: TICKETS,
    find: "    if ticket is None or not access.can_see(person, ticket):\n        raise NotFound(access.cannot_see(person, ticket_id))",
    replace:
      '    if ticket is None:\n        raise NotFound(access.cannot_see(person, ticket_id))\n    if not access.can_see(person, ticket):\n        raise NotFound(f"Ticket {ticket_id} is assigned to someone else.")',
    run: pytest(`${TOOL_ACCESS}::test_a_missing_ticket_and_one_you_cannot_see_get_the_same_answer`),
  },
  {
    guard: "access: lists and counts hold only what the person can see",
    file: TICKETS,
    find: "return [t for t in list_tickets(conn, status) if access.can_see(person, t)]",
    replace: "return list_tickets(conn, status)",
    run: pytest(`${TOOL_ACCESS}::test_lists_and_counts_hold_only_what_the_person_can_see`),
  },
  {
    guard: "access: a customer's other tickets are trimmed to what the person can see",
    file: TICKETS,
    find: 'if other["id"] != ticket_id and access.can_see(person, other)',
    replace: 'if other["id"] != ticket_id',
    run: pytest(`${TOOL_ACCESS}::test_the_customers_other_tickets_are_trimmed_too`),
  },
  {
    guard: "access: the narrow set's customer lookups are trimmed too",
    file: TICKETS,
    find: "return [t for t in rows if access.can_see(person, t)]",
    replace: "return rows",
    run: pytest(`${TOOL_ACCESS}::test_the_narrow_set_keeps_the_same_rule`),
  },
  {
    guard: "triage: the tools act for the person the assistant was started for",
    file: "python/src/helpdesk/triage.py",
    find: 'tools = triage_tools(conn, person).only(agent["tools"])',
    replace: 'tools = triage_tools(conn, access.find_person(conn, "sam")).only(agent["tools"])',
    run: pytest("tests/test_triage_cli.py::test_the_demo_says_who_the_assistant_acts_for_and_its_tools_act_for_them"),
  },
  {
    guard: "arguments: an argument the schema doesn't have is refused",
    file: TOOLS,
    find: "        if name not in properties\n",
    replace: "        if False\n",
    run: pytest(`${TOOL_ACCESS}::test_the_model_cannot_choose_whose_permissions_to_use`),
  },
  {
    guard: "arguments: a value outside an enum is refused, naming the values allowed",
    file: TOOLS,
    find: "        if not same:\n",
    replace: "        if False:\n",
    run: pytest(`${TOOL_ARGS}::test_every_problem_is_reported_at_once`),
  },
  {
    guard: "arguments: an enum value in another case is taken as the schema's own",
    file: TOOLS,
    find: "        value = same[0]\n",
    replace: "        value = value\n",
    run: pytest(`${TOOL_ARGS}::test_an_enum_value_in_another_case_is_taken_as_the_schemas_own`),
  },
  {
    guard: "arguments: a number below the minimum is refused",
    file: TOOLS,
    find: '    if "minimum" in rules and value < rules["minimum"]:',
    replace: "    if False:",
    run: pytest(`${TOOL_ARGS}::test_a_number_below_the_minimum_is_refused`),
  },
  {
    guard: "arguments: text that is only spaces is refused",
    file: TOOLS,
    find: 'if "minLength" in rules and len(value.strip()) < rules["minLength"]:',
    replace: 'if "minLength" in rules and len(value) < rules["minLength"]:',
    run: pytest(`${TOOL_ARGS}::test_empty_text_is_refused`),
  },
  {
    guard: "arguments: every problem is reported at once",
    file: TOOLS,
    find: "    return fixed, problems\n",
    replace: "    return fixed, problems[:1]\n",
    run: pytest(`${TOOL_ARGS}::test_every_problem_is_reported_at_once`),
  },
  {
    guard: "arguments: nothing runs when the arguments are wrong",
    file: TOOLS,
    find: "        if problems:\n",
    replace: "        if False:\n",
    run: pytest(`${TOOL_ARGS}::test_nothing_runs_when_the_arguments_are_wrong`),
  },
  {
    guard: "arguments: a toolbox refuses a tool whose schema has a rule it can't check",
    file: TOOLS,
    find: "        if unchecked:\n",
    replace: "        if False:\n",
    run: pytest(`${TOOL_ARGS}::test_a_toolbox_refuses_a_schema_rule_it_cant_check`, `${TOOL_ARGS}::test_every_keyword_the_adapter_strips_is_checked_or_refused`),
  },
  {
    guard: "arguments: an argument's keyword the toolbox doesn't check is refused",
    file: TOOLS,
    find: '        found += [f"{spec.name}.{name}\'s {key!r}" for key in rules if key not in ARGUMENT_KEYWORDS[kind]]\n',
    replace: "",
    run: pytest(`${TOOL_ARGS}::test_every_keyword_the_adapter_strips_is_checked_or_refused`),
  },
  {
    guard: "arguments: an argument of a type the toolbox doesn't check is refused",
    file: TOOLS,
    find: '            found.append(f"{spec.name}.{name}\'s type {kind!r}")\n',
    replace: "",
    run: pytest(`${TOOL_ARGS}::test_a_toolbox_refuses_a_schema_rule_it_cant_check`),
  },
  {
    guard: "arguments: a keyword at the top of a schema the toolbox doesn't check is refused",
    file: TOOLS,
    find: '    found = [f"{spec.name}\'s {key!r}" for key in schema if key not in SCHEMA_KEYWORDS]\n',
    replace: "    found = []\n",
    run: pytest(`${TOOL_ARGS}::test_a_toolbox_refuses_a_schema_rule_it_cant_check`),
  },
  {
    guard: "arguments: a keyword the adapter strips isn't listed as checked unless checked_value checks it",
    file: TOOLS,
    find: '    "integer": frozenset({"type", "description", "enum", "minimum", "maximum"}),\n',
    replace: '    "integer": frozenset({"type", "description", "enum", "minimum", "maximum", "exclusiveMinimum"}),\n',
    run: pytest(`${TOOL_ARGS}::test_every_keyword_the_adapter_strips_is_checked_or_refused`),
  },
  {
    guard: "results: a result over the limit is cut, and says how to ask for less",
    file: TOOLS,
    find: "        if len(content) <= self.max_result_chars:\n",
    replace: "        if True:\n",
    run: pytest(`${TOOL_RESULTS}::test_a_result_over_the_limit_is_cut_at_a_line_and_says_how_to_ask_for_less`),
  },
  {
    guard: "results: a cut ends at a whole line",
    file: TOOLS,
    find: '            cut = cut[: cut.rindex("\\n")]\n',
    replace: "            cut = cut\n",
    run: pytest(`${TOOL_RESULTS}::test_a_result_over_the_limit_is_cut_at_a_line_and_says_how_to_ask_for_less`),
  },
  {
    guard: "results: a page that isn't the last says how to get the next",
    file: TOOLS,
    find: '            lines.append(f"More on page {n}: call find_tickets again with the same filters and page {n}.")\n',
    replace: "            pass\n",
    run: pytest(`${TOOL_RESULTS}::test_a_page_says_how_many_match_and_how_to_get_the_next`),
  },
  {
    guard: "results: a page past the end is refused, naming the last page",
    file: TICKETS,
    find: "    if page > pages:\n",
    replace: "    if False:\n",
    run: pytest(`${TOOL_RESULTS}::test_a_page_past_the_end_names_the_last_page`),
  },
  {
    guard: "results: an unexpected failure comes back as a result that says not to retry",
    file: TOOLS,
    find: "        except Exception as e:\n",
    replace: "        except ZeroDivisionError as e:\n",
    run: pytest(`${TOOL_RESULTS}::test_an_unexpected_failure_says_not_to_retry_and_logs_the_traceback`),
  },
  {
    guard: "strict: a strict tool goes out marked strict",
    file: ADAPTER,
    find: 'return {"name": tool.name, "description": tool.description, "input_schema": schema, "strict": True}',
    replace: 'return {"name": tool.name, "description": tool.description, "input_schema": schema}',
    run: pytest(`${ADAPTER_TESTS}::test_a_strict_tool_goes_out_marked_strict_without_the_keywords_strict_mode_refuses`),
  },
  {
    guard: "strict: the keywords strict mode refuses are left out of what is sent",
    file: ADAPTER,
    find: '        if key in STRICT_UNSUPPORTED or (key == "minItems" and value not in (0, 1)):\n',
    replace: "        if False:\n",
    run: pytest(`${ADAPTER_TESTS}::test_a_strict_tool_goes_out_marked_strict_without_the_keywords_strict_mode_refuses`),
  },
  {
    guard: "strict: an object open to extra arguments is refused before anything is sent",
    file: ADAPTER,
    find: '    if schema.get("type") == "object" and schema.get("additionalProperties") is not False:\n',
    replace: "    if False:\n",
    run: pytest(`${ADAPTER_TESTS}::test_a_strict_object_that_allows_extra_properties_is_refused_before_sending`),
  },
  {
    guard: "strict: no more strict tools in one request than the provider allows",
    file: ADAPTER,
    find: "            if len(strict) > MAX_STRICT_TOOLS:\n",
    replace: "            if False:\n",
    run: pytest(`${ADAPTER_TESTS}::test_more_strict_tools_than_one_request_may_carry_are_refused_before_sending`),
  },
  {
    guard: "tool definitions: a parameter without a description fails the build",
    file: TOOLS,
    find: '"description": "What to look for, in words."',
    replace: '"description": ""',
    run: pytest(`${TOOL_DEFS}::test_every_tool_is_described_well_enough_to_reason_from`),
  },
  {
    guard: "tool definitions: a tool that isn't strict fails the build",
    file: "python/src/helpdesk/assistant/narrow.py",
    find: "return ToolSpec(name, description, schema, strict=True)",
    replace: "return ToolSpec(name, description, schema)",
    run: pytest(`${TOOL_DEFS}::test_every_tool_is_described_well_enough_to_reason_from`),
  },
  {
    guard: "tool definitions: a description under three sentences is caught",
    file: `python/${TOOL_DEFS}`,
    find: "    if sentences(spec.description) < MIN_SENTENCES:\n",
    replace: "    if False:\n",
    run: pytest(`${TOOL_DEFS}::test_a_thin_definition_is_caught_with_each_problem_named`),
  },
  {
    guard: "tool definitions: an ambiguous parameter name is caught",
    file: `python/${TOOL_DEFS}`,
    find: "        if name in AMBIGUOUS:\n",
    replace: "        if False:\n",
    run: pytest(`${TOOL_DEFS}::test_a_thin_definition_is_caught_with_each_problem_named`),
  },
  {
    guard: "compare: both tool sets must gather the facts each task needs",
    file: "python/src/helpdesk/tools.py",
    find: '                    ("list_customer_tickets", {"customer_id": 2}),\n',
    replace: "",
    run: pytest("tests/test_tools_cli.py::test_both_sets_see_the_facts_each_task_needs"),
  },

  // Chapter 12: the MCP server, one more way in to the same tools, for the same person.
  {
    guard: "mcp: the server never chooses a person itself",
    file: MCP_SERVER,
    find: 'who = os.environ.get(STAFF_VARIABLE, "").strip()',
    replace: 'who = os.environ.get(STAFF_VARIABLE, "dana").strip()',
    run: pytest(`${MCP}::test_the_server_refuses_to_start_without_a_person_it_knows`),
  },
  {
    guard: "mcp: the tools act for the person in the server's environment",
    file: MCP_SERVER,
    find: "toolbox: Toolbox = triage_tools(conn, person)",
    replace: 'toolbox: Toolbox = triage_tools(conn, access.find_person(conn, "dana"))',
    run: pytest(`${MCP}::test_the_tools_act_for_the_person_in_the_servers_environment`),
  },
  {
    guard: "mcp: a ticket resource applies the same rule as the tools",
    file: MCP_SERVER,
    find: "ticket = tickets.visible_ticket(conn, person, int(number))",
    replace: "ticket = tickets.get_ticket(conn, int(number))",
    run: pytest(`${MCP}::test_one_person_cannot_see_anothers_ticket_through_any_way_in`),
  },
  {
    guard: "mcp: a ticket record is never kept for anyone else",
    file: MCP_SERVER,
    find: 'return types.ReadResourceResult(contents=[record], ttl_ms=0, cache_scope="private")',
    replace: 'return types.ReadResourceResult(contents=[record], ttl_ms=3_600_000, cache_scope="public")',
    run: pytest(`${MCP}::test_a_ticket_record_is_never_kept_for_anyone_else`),
  },
  {
    guard: "mcp: the prompt holds only a ticket the person may see",
    file: MCP_SERVER,
    find: "        if ticket.is_error:\n",
    replace: "        if False:\n",
    run: pytest(`${MCP}::test_one_person_cannot_see_anothers_ticket_through_any_way_in`),
  },
  {
    guard: "mcp: a tool call's failure comes back marked isError",
    file: MCP_SERVER,
    find: "content=[types.TextContent(text=result.content)], is_error=result.is_error",
    replace: "content=[types.TextContent(text=result.content)], is_error=False",
    run: pytest(`${MCP}::test_bad_arguments_come_back_as_a_result_the_model_can_act_on`),
  },
  {
    guard: "mcp: an unknown tool is a protocol error",
    file: MCP_SERVER,
    find: "        if params.name not in names:\n",
    replace: "        if False:\n",
    run: pytest(`${MCP}::test_an_unknown_tool_is_a_protocol_error_that_names_the_tools`),
  },
  {
    guard: "mcp: a resource URI that names nothing is refused as not found",
    file: MCP_SERVER,
    find: "if not uri.startswith((TICKETS, ARTICLES)) or not number.isdigit():",
    replace: "if False:",
    run: pytest(`${MCP}::test_a_uri_that_names_nothing_is_refused`),
  },
  {
    guard: "mcp: a missing resource gets the code of the revision the client speaks",
    file: MCP_SERVER,
    find: "code = RESOURCE_NOT_FOUND if ctx.protocol_version in HANDSHAKE_PROTOCOL_VERSIONS else INVALID_PARAMS",
    replace: "code = INVALID_PARAMS",
    run: pytest(`${MCP}::test_a_missing_resource_gets_the_code_of_the_revision_the_client_speaks`),
  },
  {
    guard: "mcp: standard output carries only MCP messages",
    file: MCP_SERVER,
    find: 'print(f"helpdesk MCP server: acting for {person.label}, on stdio.", file=sys.stderr)',
    replace: 'print(f"helpdesk MCP server: acting for {person.label}, on stdio.")',
    run: pytest(`${MCP}::test_standard_output_carries_only_mcp_messages_and_the_server_exits_when_its_input_closes`),
  },
  {
    guard: "import-linter: only helpdesk.mcp_server imports the MCP SDK",
    file: "python/pyproject.toml",
    find: 'allowed_importers = ["helpdesk.mcp_server"]',
    replace: 'allowed_importers = ["helpdesk"]',
    run: pytest(`${LAYERS}::test_a_service_importing_the_mcp_sdk_is_caught_with_the_fix`),
  },
  {
    guard: "import-linter: the MCP contract says how to fix it",
    file: "python/pyproject.toml",
    find: 'broken_contract_guidance = "Only helpdesk/mcp_server.py may use the MCP SDK. Put the rule in helpdesk.services or the toolbox, where every way in applies it, and have the server call that."\n',
    replace: "",
    run: pytest(`${LAYERS}::test_a_service_importing_the_mcp_sdk_is_caught_with_the_fix`),
  },

  // Chapter 13: governing MCP servers. The token checks, the scopes, the audit log and the catalog.
  {
    guard: "tokens: a token issued for another server is refused",
    file: TOKENS,
    find: "        if self.audience not in [canonical(str(a)) for a in audiences]:\n",
    replace: "        if False:\n",
    run: pytest(`${TOKEN_TESTS}::test_a_token_issued_for_another_server_is_refused_however_valid_it_is_there`),
  },
  {
    guard: "tokens: a token from another issuer is refused",
    file: TOKENS,
    find: "                issuer=self.issuer,\n",
    replace: "",
    run: pytest(`${TOKEN_TESTS}::test_a_token_from_another_issuer_is_refused`),
  },
  {
    guard: "tokens: an expired token is refused",
    file: TOKENS,
    find: 'options={"require": REQUIRED, "verify_aud": False},',
    replace: 'options={"require": REQUIRED, "verify_aud": False, "verify_exp": False},',
    run: pytest(`${TOKEN_TESTS}::test_an_expired_token_is_refused`),
  },
  {
    guard: "tokens: every claim RFC 9068 requires must be there",
    file: TOKENS,
    find: 'options={"require": REQUIRED, "verify_aud": False},',
    replace: 'options={"verify_aud": False},',
    run: pytest(`${TOKEN_TESTS}::test_a_token_missing_a_claim_rfc_9068_requires_is_refused`),
  },
  {
    guard: "tokens: only an access token is accepted",
    file: TOKENS,
    find: '        if str(header.get("typ", "")).lower() not in TOKEN_TYPES:\n',
    replace: "        if False:\n",
    run: pytest(`${TOKEN_TESTS}::test_a_signed_jwt_that_isnt_an_access_token_is_refused`),
  },
  {
    guard: "front door: an operation needs its scope",
    file: FRONT_DOOR,
    find: "        missing = [s for s in needed if s not in grant.scopes]",
    replace: "        missing: list[str] = []",
    run: pytest(`${HTTP_TESTS}::test_a_scope_narrows_what_a_person_may_do_and_never_widens_it`),
  },
  {
    guard: "front door: the token never reaches the MCP server",
    file: FRONT_DOOR,
    find: "                app, without_authorization(scope), replay(body, receive), send\n",
    replace: "                app, scope, replay(body, receive), send\n",
    run: pytest(`${HTTP_TESTS}::test_the_token_never_reaches_the_mcp_server`),
  },
  // Chapter 13, after the 2026-09-30 review: the attempt is recorded before the server acts, then
  // the outcome, so a request that fails on the way still leaves a record.
  {
    guard: "front door: a request passed to the server is recorded before it runs",
    file: FRONT_DOOR,
    find: "        self.audit.record(**record, status=None, outcome=ATTEMPT)\n",
    replace: "",
    run: pytest(`${HTTP_TESTS}::test_a_request_whose_handling_fails_is_still_on_record`),
  },
  {
    guard: "front door: a request whose handling fails is recorded with how it failed",
    file: FRONT_DOOR,
    find: '            self.audit.record(**record, status=500, outcome=f"failed: {type(error).__name__}")\n',
    replace: "",
    run: pytest(`${HTTP_TESTS}::test_a_request_whose_handling_fails_is_still_on_record`),
  },
  {
    guard: "front door: a request's attempt and outcome share its id",
    file: FRONT_DOOR,
    find: '            "request": uuid.uuid4().hex,\n',
    replace: "",
    run: pytest(`${HTTP_TESTS}::test_a_request_passed_to_the_server_is_recorded_before_it_runs_then_its_outcome`),
  },
  {
    guard: "audit: an attempt and its outcome read back as one request",
    file: "python/src/mcp_governance/audit.py",
    find: "        if key is not None and key in by_id:",
    replace: "        if False:",
    run: pytest(`${HTTP_TESTS}::test_a_request_passed_to_the_server_is_recorded_before_it_runs_then_its_outcome`),
  },
  {
    guard: "audit: an attempt with no outcome after it says so",
    file: "python/src/mcp_governance/audit.py",
    find: '        entry = {**r, "outcome": NO_OUTCOME} if r.get("outcome") == ATTEMPT else dict(r)',
    replace: "        entry = dict(r)",
    run: pytest(`${HTTP_TESTS}::test_an_attempt_with_no_outcome_after_it_says_so`),
  },
  {
    guard: "front door: a request without a token is audited too",
    file: FRONT_DOOR,
    find: '            self.audit.record(**record, status=401, outcome="refused 401: no token")\n',
    replace: "",
    run: pytest(`${HTTP_TESTS}::test_every_request_is_audited_and_the_token_never_is`),
  },
  {
    guard: "front door: a bad origin is refused before the token is looked at",
    file: FRONT_DOOR,
    find: "        if origin is not None and not origin_allowed(origin, self.allowed_origins):",
    replace: "        if False:",
    run: pytest(`${HTTP_TESTS}::test_a_bad_origin_is_refused_before_the_token_is_looked_at`),
  },
  {
    guard: "front door: an allowed origin's wildcard stands for a port and nothing else",
    file: FRONT_DOOR,
    find: "            and origin[len(pattern) - 1 :].isdigit()",
    replace: "            and True",
    run: pytest(`${HTTP_TESTS}::test_a_bad_origin_is_refused_before_the_token_is_looked_at`),
  },
  {
    guard: "mcp http: the front door allows the localhost origins",
    file: MCP_SERVER,
    find: "        allowed_origins=ALLOWED_ORIGINS,\n",
    replace: "",
    run: pytest(`${HTTP_TESTS}::test_a_bad_origin_is_refused_before_the_token_is_looked_at`),
  },
  {
    guard: "front door: a refusal says where the metadata is",
    file: FRONT_DOOR,
    find: "        parts.append(f'resource_metadata=\"{self.metadata_url}\"')\n",
    replace: "",
    run: pytest(`${HTTP_TESTS}::test_a_request_without_a_token_is_told_where_to_get_one`),
  },
  {
    guard: "front door: a line break Python knows, inside a record's arguments, doesn't break the log",
    file: "python/src/mcp_governance/audit.py",
    find: '.read_text(encoding="utf-8").split("\\n") if line.strip()]',
    replace: '.read_text(encoding="utf-8").splitlines() if line.strip()]',
    run: pytest(`${HTTP_TESTS}::test_a_line_break_python_knows_in_the_arguments_doesnt_break_the_log`),
  },
  {
    guard: "mcp http: a subject the server doesn't know is refused",
    file: MCP_SERVER,
    find: "person = next((p for p in access.staff(conn) if str(p.id) == subject), None)",
    replace: "person = next((p for p in access.staff(conn) if str(p.id) == subject), access.staff(conn)[0])",
    run: pytest(`${HTTP_TESTS}::test_a_subject_the_server_doesnt_know_is_refused`),
  },
  {
    guard: "mcp http: the person comes from the token",
    file: MCP_SERVER,
    find: "return None if person is None else (person.label, mcp_app_for(conn, person))",
    replace: 'return None if person is None else (person.label, mcp_app_for(conn, access.find_person(conn, "dana")))',
    run: pytest(`${HTTP_TESTS}::test_the_person_comes_from_the_token`),
  },
  {
    guard: "mcp http: a ticket resource needs tickets:read",
    file: MCP_SERVER,
    find: 'RESOURCE_SCOPES = {TICKETS: "tickets:read", ARTICLES: "kb:read"}',
    replace: 'RESOURCE_SCOPES = {ARTICLES: "kb:read"}',
    run: pytest(`${HTTP_TESTS}::test_every_way_to_a_ticket_needs_tickets_read`),
  },
  {
    guard: "mcp http: the prompt needs tickets:read",
    file: MCP_SERVER,
    find: 'PROMPT_SCOPES = {DRAFT_REPLY.name: "tickets:read"}',
    replace: "PROMPT_SCOPES: dict[str, str] = {}",
    run: pytest(`${HTTP_TESTS}::test_every_way_to_a_ticket_needs_tickets_read`),
  },
  {
    guard: "mcp http: a request from another web origin is refused",
    file: MCP_SERVER,
    find: "stateless_http=True, json_response=True, host=HTTP_HOST",
    replace: 'stateless_http=True, json_response=True, host="0.0.0.0"',
    run: pytest(`${HTTP_TESTS}::test_the_mcp_server_behind_the_front_door_refuses_another_origin_too`),
  },
  {
    guard: "mcp http: the server is compared with its catalog entry",
    file: MCP_SERVER,
    find: "    problems = offered_differs(server, tools=offered, scopes=SCOPES_SUPPORTED)",
    replace: "    problems: list[str] = []",
    run: pytest(`${HTTP_TESTS}::test_the_server_offers_exactly_what_the_catalog_approved`),
  },
  {
    guard: "mcp http: Ctrl+C stops the server cleanly",
    file: MCP_SERVER,
    find: "        except KeyboardInterrupt:\n            pass\n",
    replace: "",
    run: pytest(`${HTTP_TESTS}::test_the_server_stops_cleanly_when_interrupted`),
  },
  {
    guard: "catalog: a tool the catalog didn't approve is found",
    file: CATALOG,
    find: "        for extra in [x for x in offered if x not in approved]:",
    replace: "        for extra in []:",
    run: pytest(`${HTTP_TESTS}::test_the_server_offers_exactly_what_the_catalog_approved`),
  },
  {
    guard: "catalog: an all-granting scope is refused",
    file: CATALOG,
    find: "        elif scope.lower() in omnibus:",
    replace: "        elif False:",
    run: catalogFixture("fail-all-granting-scope"),
  },
  {
    guard: "catalog: a server anywhere else must use HTTPS",
    file: CATALOG,
    find: '    if parts.scheme == "http" and shown_host not in local_hosts:',
    replace: "    if False:",
    run: catalogFixture("fail-plain-http-elsewhere"),
  },
  {
    guard: "catalog: a field of the other transport is refused",
    file: CATALOG,
    find: "        elif key not in expected and transport in BY_TRANSPORT:",
    replace: "        elif False:",
    run: catalogFixture("fail-command-on-http"),
  },
  {
    guard: "catalog: a server listed twice is refused",
    file: CATALOG,
    find: "            if key in seen:",
    replace: "            if False:",
    run: catalogFixture("fail-listed-twice"),
  },
  {
    guard: "catalog: a server with no tools is refused",
    file: CATALOG,
    find: "        if not tools:",
    replace: "        if False:",
    run: catalogFixture("fail-no-tools"),
  },
  {
    guard: "catalog: the allowlist never matches a server by its name",
    file: CATALOG,
    find: '{"serverUrl": s["url"]} if s["transport"] == "http" else {"serverCommand": s["command"]}',
    replace: '{"serverName": s["name"]}',
    run: pytest(`${CATALOG_TESTS}::test_the_allowlist_names_each_server_by_address_or_exact_command_never_by_name`),
  },

  // Chapter 14: evaluator and optimizer, orchestrator and workers.
  {
    guard: "revise: the loop stops at its round limit",
    file: REVISE,
    find: "    for number in range(1, max_rounds + 1):",
    replace: "    for number in range(1, max_rounds + 100):",
    run: pytest(`${REVISE_TESTS}::test_a_drafter_that_never_fixes_it_stops_at_the_round_limit`),
  },
  {
    guard: "revise: a draft is accepted only when the check passes",
    file: REVISE,
    find: "        if report.ok:",
    replace: "        if True:",
    run: pytest(`${REVISE_TESTS}::test_a_draft_that_fails_the_check_goes_back_and_the_revision_is_accepted`),
  },
  {
    guard: "revise: the check's findings go back to the drafter",
    file: REVISE,
    find: "        request = feedback(report)",
    replace: "        request = task",
    run: pytest(`${REVISE_TESTS}::test_the_revision_request_carries_the_problem_the_check_found`),
  },
  {
    guard: "revise: an unchanged draft stops the loop",
    file: REVISE,
    find: "        if unchanged:",
    replace: "        if False:",
    run: pytest(`${REVISE_TESTS}::test_an_unchanged_draft_stops_the_loop_before_the_limit`),
  },
  {
    guard: "team: a customer is delegated once",
    file: TEAM,
    find: "        if not waiting:",
    replace: "        if False:",
    run: pytest(`${TEAM_TESTS}::test_a_customer_delegated_twice_is_refused_and_keeps_one_worker`),
  },
  {
    guard: "team: a customer outside the batch is refused",
    file: TEAM,
    find: "        if not named:",
    replace: "        if not customers:",
    run: pytest(`${TEAM_TESTS}::test_an_unknown_customer_is_refused_with_how_to_name_one`),
  },
  {
    guard: "team: workers get only the reading tools",
    file: TEAM,
    find: 'WORKER_TOOLS = ("get_ticket", "search_kb")',
    replace: 'WORKER_TOOLS = ("get_ticket", "search_kb", "find_tickets")',
    run: pytest(`${TEAM_TESTS}::test_each_worker_starts_with_only_its_brief_and_only_reading_tools`),
  },
  {
    guard: "team: a worker that stops without drafts is recorded as failed",
    file: TEAM,
    find: "            self.workers[label] = Worker(label, ids, None, None, str(stop))\n",
    replace: "",
    run: pytest(`${TEAM_TESTS}::test_a_worker_that_stops_without_drafts_is_counted_as_failed_whatever_the_summary_says`),
  },
  {
    guard: "team: the batch is complete only when nothing failed or is missing",
    file: TEAM,
    find: "        return not self.failed and not self.missing",
    replace: "        return True",
    run: pytest(`${TEAM_TESTS}::test_a_worker_that_stops_without_drafts_is_counted_as_failed_whatever_the_summary_says`),
  },
  {
    guard: "team: a customer never delegated is counted as missing",
    file: TEAM,
    find: "        missing = tuple(c for c in batch if c not in self.workers)",
    replace: "        missing = ()",
    run: pytest(`${TEAM_TESTS}::test_a_customer_never_delegated_is_missing`),
  },
  {
    guard: "team: a worker's drafts count only when their citations hold",
    file: TEAM,
    find: "            and self.report.ok\n",
    replace: "",
    run: pytest(`${TEAM_TESTS}::test_a_worker_whose_citations_fail_is_not_counted_as_drafted`),
  },
  {
    guard: "team: a worker's drafts count only when it read every ticket",
    file: TEAM,
    find: "            and not self.unread\n",
    replace: "",
    run: pytest(`${TEAM_TESTS}::test_a_worker_that_skips_a_ticket_is_not_counted`),
  },
  {
    guard: "team: the count is made even when the orchestrator stops",
    file: TEAM,
    find: "        return TeamRun(None, tuple(team.workers.values()), team.account(), str(stop))",
    replace: "        raise",
    run: pytest(`${TEAM_TESTS}::test_the_count_is_made_even_when_the_orchestrator_stops_part_way`),
  },
  {
    guard: "team: a draft counts only when it cites at least one passage",
    file: TEAM,
    find: "            and self.report.checked > 0\n",
    replace: "",
    run: pytest(`${TEAM_TESTS}::test_a_worker_whose_answer_cites_nothing_is_not_counted`),
  },
  {
    guard: "team: an empty answer is named as empty",
    file: TEAM,
    find: '        if self.empty:\n            return "its worker\'s answer was empty, so there are no drafts."\n',
    replace: "",
    run: pytest(`${TEAM_TESTS}::test_a_worker_that_answers_with_nothing_is_not_counted`),
  },
  {
    guard: "team: sentences that cite nothing are reported",
    file: TEAM,
    find: '            out.append(f"In those drafts, {citing_nothing(sum(self.uncited.values()))}: {each}.")',
    replace: "            pass",
    run: pytest(`${TEAM_TESTS}::test_a_greeting_without_a_citation_doesnt_stop_a_draft_counting_but_is_reported`),
  },
  {
    guard: "team: the batch is grouped by customer id, not name",
    file: TICKETS,
    find: '        grouped.setdefault(ticket["customer_id"], []).append(ticket)',
    replace: '        grouped.setdefault(ticket["customer_name"], []).append(ticket)',
    run: pytest(`${TEAM_TESTS}::test_two_customers_with_one_name_are_two_customers`),
  },
  {
    guard: "team: a shared name carries the customer id in its label",
    file: TEAM,
    find: '(f"{names[cid]} (customer {cid})" if names[cid] in shared else names[cid])',
    replace: "names[cid]",
    run: pytest(`${TEAM_TESTS}::test_two_customers_with_one_name_are_two_customers`),
  },
  {
    guard: "team: a shared name delegated again goes to the customer not yet delegated",
    file: TEAM,
    find: "        label = waiting[0]",
    replace: "        label = named[0]",
    run: pytest(`${TEAM_TESTS}::test_a_shared_name_delegated_again_goes_to_the_other_customer`),
  },
  {
    guard: "team: the report says another customer has the same name",
    file: TEAM,
    find: "        others = waiting[1:]",
    replace: "        others = []",
    run: pytest(`${TEAM_TESTS}::test_a_shared_name_delegates_one_customer_at_a_time_and_the_count_names_each`),
  },
  {
    guard: "team: the batch is the open and pending tickets only",
    file: TICKETS,
    find: '    rows = [t for t in visible_tickets(conn, person) if t["status"] in ACTIVE]',
    replace: "    rows = visible_tickets(conn, person)",
    run: pytest(`${TEAM_TESTS}::test_the_batch_is_every_open_or_pending_ticket_the_person_can_see_by_customer`),
  },
  {
    guard: "patterns: nothing runs when a definition breaks the policy",
    file: "python/src/helpdesk/patterns.py",
    find: "        for v in check(d, policy)",
    replace: "        for v in []",
    run: pytest("tests/test_patterns_compare.py::test_nothing_runs_when_a_definition_breaks_the_policy"),
  },

  // The fix loop's protected list, derived from the checks (a review, 2026-09-26): each check's code
  // and data, a tool's configuration anywhere, file-wide silencing, and HEAD watched.
  {
    guard: "fix loop: every check's listed files feed the protected list",
    file: PROTECTED_MJS,
    find: "export const PROTECTED = [...ALWAYS, ...new Set(Object.values(CHECK_FILES).flat()), CONFIG_NAMES];",
    replace: "export const PROTECTED = [...ALWAYS, CONFIG_NAMES];",
    run: nodeTest(LOOP_TESTS, "the checks' records and data stop the loop"),
  },
  {
    guard: "fix loop: a check without its files listed fails the test",
    file: PROTECTED_MJS,
    find: '  "Agent definitions (python -m agent_policy)": [',
    replace: '  "Agent definitions": [',
    run: nodeTest(PROTECTED_TESTS, "every check node check.mjs runs has its files listed"),
  },
  {
    guard: "fix loop: what check.mjs runs is covered (the API contract's module)",
    file: PROTECTED_MJS,
    find: "[/^python\\/src\\/helpdesk\\/contract\\.py$/]",
    replace: "[]",
    run: nodeTest(PROTECTED_TESTS, "what check.mjs runs is protected"),
  },
  {
    guard: "fix loop: a new ruff.toml is a change to the checks, in any folder",
    file: PROTECTED_MJS,
    find: "      String.raw`\\.?ruff\\.toml`,\n",
    replace: "",
    run: nodeTest(LOOP_TESTS, "a new tool configuration file stops the loop"),
  },
  {
    guard: "fix loop: a .gitignore is a change to the checks",
    file: PROTECTED_MJS,
    find: "      String.raw`\\.gitignore`,\n",
    replace: "",
    run: nodeTest(LOOP_TESTS, "hiding a new configuration file from git"),
  },
  {
    guard: "fix loop: git's info/exclude is watched",
    file: "tools/fix-loop.mjs",
    find: 'const GIT_OWN = ["info/exclude", "config"];',
    replace: 'const GIT_OWN = ["config"];',
    run: nodeTest(LOOP_TESTS, "hiding a new configuration file from git"),
  },
  {
    guard: "fix loop: an attempt that moves HEAD stops the loop",
    file: "tools/fix-loop.mjs",
    find: "  const moved = now !== start;",
    replace: "  const moved = false;",
    run: nodeTest(LOOP_TESTS, "a commit stops the loop"),
  },
  {
    guard: "fix loop: the prompt says a commit stops the run",
    file: "tools/fix-loop.mjs",
    find: " A commit, or a checkout of another commit, stops the run too.",
    replace: "",
    run: nodeTest(LOOP_TESTS, "the prompt says a commit stops the run"),
  },

  // Chapter 15's two structural checks, fixed after a review (2026-09-26): routers under any name,
  // and no real import of the anthropic SDK under tests/.
  {
    guard: "fitness: a router under another name is followed",
    file: ROUTES_FITNESS,
    find: "            if builds_one(value) or (isinstance(value, ast.Name) and value.id in names):",
    replace: "            if False:",
    run: pytest(`${ROUTES_FITNESS_TEST}::test_a_router_under_any_name_or_import_alias_is_followed`),
  },
  {
    guard: "fitness: an import alias of APIRouter is followed",
    file: ROUTES_FITNESS,
    find: "            constructors |= {alias.asname or alias.name for alias in node.names if alias.name in CONSTRUCTORS}",
    replace: "            constructors |= set()",
    run: pytest(`${ROUTES_FITNESS_TEST}::test_a_router_under_any_name_or_import_alias_is_followed`),
  },
  {
    guard: "fitness: a router made through the fastapi module is followed",
    file: ROUTES_FITNESS,
    find: "        return isinstance(func, ast.Attribute) and func.attr in CONSTRUCTORS and _root(func) in modules",
    replace: "        return False",
    run: pytest(`${ROUTES_FITNESS_TEST}::test_a_router_under_any_name_or_import_alias_is_followed`),
  },
  {
    guard: "fitness: a copy of a router is a router",
    file: ROUTES_FITNESS,
    find: "(isinstance(value, ast.Name) and value.id in names)",
    replace: "False",
    run: pytest(`${ROUTES_FITNESS_TEST}::test_a_router_under_any_name_or_import_alias_is_followed`),
  },
  {
    guard: "fitness: a route added with add_api_route is checked",
    file: ROUTES_FITNESS,
    find: '_on_a_router(node.func, routers, {"add_api_route"})',
    replace: "_on_a_router(node.func, routers, set())",
    run: pytest(`${ROUTES_FITNESS_TEST}::test_a_router_under_any_name_or_import_alias_is_followed`),
  },
  {
    guard: "fitness: every module in the helpdesk is read for routes",
    file: ROUTES_FITNESS,
    find: '        for path in sorted(HELPDESK.rglob("*.py"))',
    replace: '        for path in [HELPDESK / "api" / "app.py"]',
    run: pytest(`${ROUTES_FITNESS_TEST}::test_every_route_that_returns_data_declares_its_response_model`),
  },
  {
    guard: "fitness: import anthropic in a test is caught",
    file: FAKE_FITNESS,
    find: "            found = any(_is_anthropic(alias.name) for alias in node.names)",
    replace: "            found = False",
    run: pytest(`${FAKE_FITNESS_TEST}::test_every_way_to_reach_the_sdk_starts_with_an_import_that_is_caught`),
  },
  {
    guard: "fitness: from anthropic import in a test is caught",
    file: FAKE_FITNESS,
    find: "            found = node.level == 0 and _is_anthropic(node.module)",
    replace: "            found = False",
    run: pytest(`${FAKE_FITNESS_TEST}::test_every_way_to_reach_the_sdk_starts_with_an_import_that_is_caught`),
  },
  {
    guard: "fitness: the SDK loaded by name in a test is caught",
    file: FAKE_FITNESS,
    find: 'LOADERS = {"import_module", "__import__", "importorskip"}',
    replace: "LOADERS = set()",
    run: pytest(`${FAKE_FITNESS_TEST}::test_every_way_to_reach_the_sdk_starts_with_an_import_that_is_caught`),
  },
  {
    guard: "fitness: a module whose name only starts with anthropic isn't the SDK",
    file: FAKE_FITNESS,
    find: 'return bool(name) and name.split(".")[0] == "anthropic"',
    replace: 'return bool(name) and name.startswith("anthropic")',
    run: pytest(`${FAKE_FITNESS_TEST}::test_a_string_that_mentions_the_sdk_is_not_an_import`),
  },

  // Chapter 10's done check, fixed after a review (2026-09-26): a proof must be a test the runners
  // collect, found in the code, not in a string or a comment.
  {
    guard: "progress: a Python proof must be a test_*.py file",
    file: PROGRESS,
    find: "    if (!PYTHON_TEST_FILE.test(file) || (under.length && !under.some((folder) => file.startsWith(folder)))) {",
    replace: "    if (false) {",
    run: progressTest("a proof that no test runner collects fails"),
  },
  {
    guard: "progress: a Python proof must be under pytest's testpaths",
    file: PROGRESS,
    find: "    if (!PYTHON_TEST_FILE.test(file) || (under.length && !under.some((folder) => file.startsWith(folder)))) {",
    replace: "    if (!PYTHON_TEST_FILE.test(file)) {",
    run: progressTest("real tests beside the decoys still pass"),
  },
  {
    guard: "progress: a Python proof's name starts with test",
    file: PROGRESS,
    find: "    if (!/^test\\w*$/.test(name)) return",
    replace: "    if (false) return",
    run: progressTest("a proof that no test runner collects fails"),
  },
  {
    guard: "progress: a def in a Python string or comment isn't a test",
    file: PROGRESS,
    find: "    const { code } = scan(text, true);",
    replace: "    const code = text;",
    run: progressTest("a proof that no test runner collects fails"),
  },
  {
    guard: "progress: a Python test is a def at the top of the file",
    file: PROGRESS,
    find: "new RegExp(`^(async\\\\s+)?def ${escape(name)}\\\\(`, \"m\")",
    replace: "new RegExp(`^\\\\s*(async\\\\s+)?def ${escape(name)}\\\\(`, \"m\")",
    run: progressTest("a proof that no test runner collects fails"),
  },
  {
    guard: "progress: a JavaScript or TypeScript proof must be a test file",
    file: PROGRESS,
    find: "  if (!SCRIPT_TEST_FILE.test(file)) {",
    replace: "  if (false) {",
    run: progressTest("a proof that no test runner collects fails"),
  },
  {
    guard: "progress: a JavaScript title in a comment isn't a test",
    file: PROGRESS,
    find: '    if (python ? c === "#" : text.startsWith("//", i)) {',
    replace: '    if (python ? c === "#" : false) {',
    run: progressTest("a proof that no test runner collects fails"),
  },
  {
    guard: "progress: a JavaScript title inside another string isn't a test",
    file: PROGRESS,
    find: "    } else if (c === '\"' || c === \"'\" || (!python && c === \"`\")) {",
    replace: "    } else if (c === '\"' || (!python && c === \"`\")) {",
    run: progressTest("a proof that no test runner collects fails"),
  },
  {
    guard: "progress: a JavaScript regular expression isn't a test",
    file: PROGRESS,
    find: '    } else if (!python && c === "/" && ',
    replace: '    } else if (false && c === "/" && ',
    run: progressTest("a proof that no test runner collects fails"),
  },
  {
    guard: "pytest: an expected failure that passes fails the run",
    file: "python/pyproject.toml",
    find: "xfail_strict = true",
    replace: "xfail_strict = false",
    run: pytest("tests/test_pytest_settings.py::test_an_expected_failure_that_passes_fails_the_run"),
  },

  // Chapter 1: the tally counts only data it can trust.
  {
    guard: "tally: a missing field that may be null stops the run",
    file: "postings/tally.mjs",
    find: "      if (!(key in p)) problems.push(",
    replace: "      if (false) problems.push(",
    run: nodeTest("postings/tally.test.mjs", "a missing or misspelled field that may be null"),
  },
  // Chapter 1, the sample extended: the gateway signal, and the fields that date each posting.
  {
    guard: "tally: the gateway is checked like every other signal",
    file: "postings/tally.mjs",
    find: '  "gateway",\n];',
    replace: "];",
    run: nodeTest("postings/tally.test.mjs", "a missing gateway code stops the run"),
  },
  {
    guard: "tally: every posting has the day it was read",
    file: "postings/tally.mjs",
    find: "    if (!isDate(p.readOn)) {",
    replace: "    if (false) {",
    run: nodeTest("postings/tally.test.mjs", "a posting without its read date stops the run"),
  },
  {
    guard: "tally: a gateway basis is text, reread or note",
    file: "postings/tally.mjs",
    find: 'if ("gatewayBasis" in p && !GATEWAY_BASIS.includes(p.gatewayBasis)) {',
    replace: "if (false) {",
    run: nodeTest("postings/tally.test.mjs", "a gateway basis must be text, reread or note"),
  },
  {
    guard: "tally: an architect title says whether public work is asked for",
    file: "postings/tally.mjs",
    find: 'if ((isArchitect(p) || "publicWorkAsked" in p) && ',
    replace: 'if (("publicWorkAsked" in p) && ',
    run: nodeTest("postings/tally.test.mjs", "an architect title without publicWorkAsked"),
  },
  {
    guard: "tally: every exclusion record has the day it was screened",
    file: "postings/tally.mjs",
    find: "    if (isDate(e?.screenedOn)) return;",
    replace: "    return;",
    run: nodeTest("postings/tally.test.mjs", "an exclusion record without its screening date"),
  },

  // Chapter 7: the client's consumer test calls every method the client has.
  {
    guard: "contract: a client method no consumer test calls fails",
    file: "ts/src/client.ts",
    find: "  searchKb(query: string, limit = 5): Promise<KbArticle[]> {",
    replace: '  reopenTicket(id: number): Promise<Ticket> {\n    return this.#request("POST", `/tickets/${id}/reopen`);\n  }\n\n  searchKb(query: string, limit = 5): Promise<KbArticle[]> {',
    run: vitest("test/contract.test.ts", "calls every method the client has"),
  },
  // Chapter 7, after the 2026-09-30 review: the contract says what generated it.
  {
    guard: "contract: the contract says what made it",
    file: "python/src/helpdesk/contract.py",
    find: '    return {**doc, "info": {**doc["info"], "x-generated-by": GENERATED_BY}}',
    replace: "    return doc",
    run: pytest("tests/test_contract.py::test_the_contract_says_what_made_it_in_its_first_lines"),
  },

  // The script tests' git runner (tools/git-run.mjs): the caller's git setup stays out, a failure
  // carries what git printed, and only a file another program held open is tried again.
  {
    guard: "git-run: the caller's GIT_ variables are dropped",
    file: GIT_RUN,
    find: "    if (!/^GIT_/i.test(name) && !/^XDG_CONFIG_HOME$/i.test(name)) env[name] = value;",
    replace: "    env[name] = value;",
    run: gitRunTest("the caller's git configuration and GIT_ variables"),
  },
  {
    guard: "git-run: a failure carries git's stdout",
    file: GIT_RUN,
    find: '\\n--- stdout ---\\n${run.stdout ?? ""}',
    replace: "",
    run: gitRunTest("a failed call throws"),
  },
  {
    guard: "git-run: only a fatal error is tried again",
    file: GIT_RUN,
    find: "return status === 128 && /Permission",
    replace: "return /Permission",
    run: gitRunTest("only a file another program held open"),
  },
  {
    guard: "git-run: a commit that landed isn't run again",
    file: GIT_RUN,
    find: "/Permission denied|unable to write new index file/",
    replace: "/Permission denied|unable to write/",
    run: gitRunTest("only a file another program held open"),
  },
  {
    guard: "git-run: a lock another git holds isn't waited out",
    file: GIT_RUN,
    find: "/Permission denied|unable to write new index file/",
    replace: "/Permission denied|unable to write new index file|index\\.lock/",
    run: gitRunTest("only a file another program held open"),
  },
];
